#!/bin/bash
#
# Created on : Fri Mar 29 20:09:56 IST 2019
#
usage() {
	echo "Usage : dos_scf2nscf [scf_input] [nscf_input] [dos_input]"
}

export scf_input=$1
export nscf_input=$2
export dos_input=$3


if [ $# -ne 3 ] ; then
	usage
	exit 1;
fi

if test ! -f $scf_input ; then
        echo "FATAL ERROR :: $scf_input not found"
        exit 1;
fi

sed s/"ibrav = 0"/"ibrav = 0,occupations = 'tetrahedra'"/g $scf_input > temp.d0
sed s/"calculation = 'scf'"/"calculation = 'nscf'"/g temp.d0 > temp.d1

nk1=`echo "$(tail -n 1 temp.d1|gawk {'print $1'})*4"|bc`
nk2=`echo "$(tail -n 1 temp.d1|gawk {'print $2'})*4"|bc`
nk3=`echo "$(tail -n 1 temp.d1|gawk {'print $3'})*4"|bc`
nks1=`tail -n 1 temp.d1|gawk {'print $4'}`
nks2=`tail -n 1 temp.d1|gawk {'print $5'}`
nks3=`tail -n 1 temp.d1|gawk {'print $6'}`

head -n -2 temp.d1 > $nscf_input
echo "K_POINTS {automatic}" >> $nscf_input
echo $nk1 $nk2 $nk3 $nks1 $nks2 $nks3 >> $nscf_input


rm -rf temp.d*

cat > $dos_input <<EOF
&DOS
   $(grep outdir $scf_input)
      fildos = $1.dos.dat
        Emin = -50.0,
        Emax = 50.0,
      DeltaE = 0.1
/
EOF
